version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    commit-message:
      prefix: build(deps)
    labels:
      - dependencies
    open-pull-requests-limit: 10
